modLoader = "javafml"
loaderVersion = "[40,)"
#issueTrackerURL = ""
license = "GPLv3"

[[mods]]
modId = "tweakerge_compat"
version = "${version}"
displayName = "TweakergeCompat"
displayURL = "https://github.com/ThinkingStudios/TweakergeCompat"
authors = "TexTrue, ThinkingStudio"
description = '''
Fix the conflict between Tweakerge and other mods.
'''
logoFile = "icon.png"

[[dependencies.tweakerge_compat]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.tweakerge_compat]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18,1.18.2]"
ordering = "NONE"
side = "BOTH"
